# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [1]:
# Import torch
import torch

# Create random tensor
x = torch.rand(7,7)
x

tensor([[0.9248, 0.5098, 0.2332, 0.7315, 0.3417, 0.8196, 0.2136],
        [0.8685, 0.6241, 0.7693, 0.8936, 0.0121, 0.1565, 0.6175],
        [0.2769, 0.1225, 0.0795, 0.1883, 0.4822, 0.6953, 0.6454],
        [0.7203, 0.0379, 0.1517, 0.6235, 0.5838, 0.5974, 0.0483],
        [0.7953, 0.1005, 0.9889, 0.2998, 0.8437, 0.7134, 0.8574],
        [0.6249, 0.2834, 0.4031, 0.7034, 0.1034, 0.9055, 0.0172],
        [0.8556, 0.2176, 0.5859, 0.0325, 0.2458, 0.1471, 0.6526]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [2]:
# Create another random tensor
y = torch.rand(1,7)
# Perform matrix multiplication
torch.matmul(x,y.t())


tensor([[1.0156],
        [1.4186],
        [0.9814],
        [0.6841],
        [1.9681],
        [0.8850],
        [1.1441]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [5]:
# Set manual seed
random_seed = 0
torch.manual_seed(seed=random_seed)

# Create two random tensors
random1 = torch.rand(2,3)
torch.manual_seed(seed=random_seed)

random2 = torch.rand(2,3)

# Matrix multiply tensors
print(random1)
print(random2)
random1 @ random2.t()

tensor([[0.4963, 0.7682, 0.0885],
        [0.1320, 0.3074, 0.6341]])
tensor([[0.4963, 0.7682, 0.0885],
        [0.1320, 0.3074, 0.6341]])


tensor([[0.8443, 0.3578],
        [0.3578, 0.5140]])

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [10]:
# Set random seed on the GPU
gpu_seed = 1234


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [30]:
# Set random seed
torch.cuda.manual_seed(seed = gpu_seed)

# Check for access to GPU
print("Device:", "cuda" if torch.cuda.is_available() else "cpu")

# Create two random tensors on GPU
gpu_t1 = torch.rand(2,3,device="cuda")
torch.cuda.manual_seed(seed = gpu_seed)

gpu_t2 = torch.rand(2,3, device="cuda")
print(gpu_t1)
print(gpu_t2)

Device: cuda
tensor([[0.1272, 0.8167, 0.5440],
        [0.6601, 0.2721, 0.9737]], device='cuda:0')
tensor([[0.1272, 0.8167, 0.5440],
        [0.6601, 0.2721, 0.9737]], device='cuda:0')



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [48]:
# Perform matmul on tensor_A and tensor_B
x = torch.matmul(gpu_t1,gpu_t2.t())
print(x,x.shape)

tensor([[0.9792, 0.8358],
        [0.8358, 1.4578]], device='cuda:0') torch.Size([2, 2])


### 8. Find the maximum and minimum values of the output of 7.

In [51]:
# Find max
print(x.max())
# Find min
print(x.min())

tensor(1.4578, device='cuda:0')
tensor(0.8358, device='cuda:0')


### 9. Find the maximum and minimum index values of the output of 7.

In [52]:
# Find arg max
print(x.argmax())

# Find arg min
print(x.argmin())

tensor(3, device='cuda:0')
tensor(1, device='cuda:0')



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [68]:
# Set seed
random_seed = 7
torch.manual_seed(random_seed)

# Create random tensor
x10 = torch.rand(1,1,1,10)
print(x10,x10.shape)
# Remove single dimensions
x10 = x10[0,0,0,:]
print(x10,x10.shape)
# Print out tensors and their shapes


tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
